export const PHONE_AUTH_START = "PHONE_AUTH_START";
export const PHONE_AUTH_SUCCESS = "PHONE_AUTH_SUCCESS";
export const PHONE_AUTH_FAIL = "PHONE_AUTH_FAIL";
export const PHONE_AUTH_SMS_SENT = "PHONE_AUTH_SMS_SENT";

export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const SIGN_UP_START = "SIGN_UP_START";
export const SIGN_UP_PHONE_LINK_SUCCESS = "SIGN_UP_PHONE_LINK_SUCCESS";
export const SIGN_UP_PHONE_LINK_FAIL = "SIGN_UP_PHONE_LINK_FAIL";
export const SIGN_UP_SUCCESS = "SIGN_UP_SUCCESS";
export const SIGN_UP_FAIL = "SIGN_UP_FAIL";

export const PASSWORD_RESET_SUCCESS = "PASSWORD_RESET_SUCCESS";
export const PASSWORD_RESET_FAIL = "PASSWORD_RESET_FAIL";

export const RESET_SUCCESS = "RESET_SUCCESS";
export const RESET_ERRORS_ON_AUTH_LINK_CHANGE = "RESET_ERRORS_ON_AUTH_LINK_CHANGE";

/* Deletes user if it has not been signed up */
export const DELETE_NEW_USER = "DELETE_NEW_USER";

export const FIRESTORE_START = "FIRESTORE_START"
export const CREATE_NEW_USER_IN_FIRESTORE = 'CREATE_NEW_USER_IN_FIRESTORE';
export const LOAD_USER_FROM_FIRESTORE = 'LOAD_USER_FROM_FIRESTORE';
export const FIRESTORE_SUCCESS = "FIRESTORE_SUCCESS"